language      : php
php           : [5.6, 7.0, 7.1]
cache         : [directories : [$COMPOSER_CACHE_DIR, $HOME/.composer/cache, vendor]]
install       : composer update --no-interaction --prefer-dist
script        : vendor/bin/phpunit
notifications :
    email : false

env :
    - TESTBENCH_VERSION=3.2.* LARAVEL_VERSION=5.2.*
    - TESTBENCH_VERSION=3.3.* LARAVEL_VERSION=5.3.*
    - TESTBENCH_VERSION=3.4.* LARAVEL_VERSION=5.4.*
    - TESTBENCH_VERSION=3.5.* LARAVEL_VERSION=5.5.*

matrix :
    exclude :
        - php : 5.6
          env : TESTBENCH_VERSION=3.5.* LARAVEL_VERSION=5.5.*

before_install :
    - composer global require hirak/prestissimo --update-no-dev
    - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update --prefer-dist
    - composer require "orchestra/testbench-browser-kit:${TESTBENCH_VERSION}" --no-update --prefer-dist
